<?php
    
    // MODULE : BOOKING
    
    $BOOKING_STATUS_INT_PENDING = 1;
    $BOOKING_STATUS_INT_PROCESSING = 2;
    $BOOKING_STATUS_INT_FOR_PAYMENT = 3;
    $BOOKING_STATUS_INT_DONE = 4;
    $BOOKING_STATUS_INT_REJECTED = 5;

    $BOOKING_STATUS_STRING_PENDING = "Pending";
    $BOOKING_STATUS_STRING_PROCESSING = "Processing";
    $BOOKING_STATUS_STRING_FOR_PAYMENT = "For Paymnent";
    $BOOKING_STATUS_STRING_DONE = "Done";
    $BOOKING_STATUS_STRING_REJECTED = "Rejected";
?>